/*
 * Copyright 2008-2010 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package es.alvsanand.webpage.db.dao;

import es.alvsanand.webpage.AlvsanandException;

/**
 * Exception generated by some Alvsanand service
 *
 * @author alvaro.santos
 * @date 23/11/2009
 *
 */
public class DAOException extends AlvsanandException {
	/**
	 * 
	 */
	private static final long serialVersionUID = -6190951886624261357L;

	/**
	 * Default constructor
	 */
	public DAOException() {
	}

	/**
	 * @param message The message of the exception
	 */
	public DAOException(String message) {
		super(message);
	}

	/**
	 * @param cause The cause of the exception
	 */
	public DAOException(Throwable cause) {
		super(cause);
	}

	/**
	 * @param message The message of the exception
	 * @param cause The cause of the exception
	 */
	public DAOException(String message, Throwable cause) {
		super(message, cause);
	}

}
